apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: krateo-fireworks
spec:
  owner: mauro.sala@kiratech.it
  title: Krateo Fireworks
  description: Krateo Fireworks Template
  icon: fa-solid fa-fire
  tags:
    - fireworks
    - template
    - krateo
    - katy perry
  widgets:
    - title: Name and description
      description: Name your app
      properties:
        - title: Name
          key: name
          description: Unique name of the component
          required: true
        - title: Description
          description: Help others understand what this service does.
          required: true
          key: description
          default: Cause baby, you're a firework. Come on, show 'em what you're worth
        - title: Krateo namespace
          key: namespace
          default: krateo-system
          description: Krateo namespace for the stack.
          required: true
    - title: Kubernetes
      properties:
        - title: Replicas
          key: replicas
          description: Number of replicas
          type: radio
          required: true
          default: "1"
          options:
            - title: "1"
              value: "1"
            - title: "2"
              value: "2"
            - title: "3"
              value: "3"
            - title: "4"
              value: "4"
            - title: "5"
              value: "5"
    - title: Expose application
      description: Expose your application
      properties:
        - title: Host
          key: host
          description: Hostname of the application
          required: true
    - title: Git repository destination
      properties:
        - title: Endpoint
          key: ednpointName
          description: github.com / gitlab.com / bitbucket.org
          required: true
          default: github.com
          type: select
          options:
            - title: github.com
              value: github.com
        - title: Organization Name
          description: Organization Name
          default: krateoplatformops
          required: true
          readOnly: true
          key: organizationName
        - title: Repo Name
          required: true
          description: Repo Name
          key: repositoryName
