apiVersion: krateo.io/v1alpha1
kind: Template
metadata:
  name: Krateo Fireworks
  annotations:
    title: Krateo Fireworks
    description: Krateo Fireworks Template
    icon: fa-solid fa-fire
    owner: mauro.sala@kiratech.it
  labels:
    tags:
      - fireworks
      - template
      - krateo
      - katy perry
spec:
  widgets:
    - title: name
